
FROM node:20.5.0

WORKDIR /src

COPY package*.json ./

ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_AUTH_DOMAIN
ARG REACT_APP_PROJECT_ID
ARG REACT_APP_STORAGE_BUCKET
ARG REACT_APP_MESSAGINGSENDERID
ARG REACT_APP_APP_ID
ARG REACT_APP_MEASUREMENT_ID


ENV REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_AUTH_DOMAIN=$REACT_APP_AUTH_DOMAIN
ENV REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID
ENV REACT_APP_STORAGE_BUCKET=$REACT_APP_STORAGE_BUCKET
ENV REACT_APP_MESSAGINGSENDERID=$REACT_APP_MESSAGINGSENDERID
ENV REACT_APP_APP_ID=$REACT_APP_APP_ID
ENV REACT_APP_MEASUREMENT_ID=$REACT_APP_MEASUREMENT_ID

RUN npm install

COPY . .
RUN npm run build

CMD [ "npm", "start" ]
